baseURL: "https://chris-nemeth.github.io" 
title: Chris Nemeth
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Books
          url: books/
          weight: 5 
        - name: Software 
          url: software/
          weight: 4 
        - name: Code 
          url: code_and_software/
          weight: 4 
        - name: Group
          url: research_group/
        - name: Blog
          url: blogs/
          weight: 6

params:
    description: "I am a Professor in Probabilistic Machine Learning at Lancaster University."
    author: Chris Nemeth
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","books","software","code","group"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Chris Nemeth
          subtitle: "I am a Professor in Probabilistic Machine Learning at Lancaster University. My current research focuses on gradient flow methods for the development of optimisation and sampling algorithms to efficiently estimate the parameters of large-scale models. I also work on Monte Carlo methods for Bayesian inference, Gaussian processes, statistical network modelling and the application of probabilistic modelling to environmental challenges."
          imageUrl: "chris2024.png"
          imageWidth: 234
          imageHeight: 353
          imageTitle: Chris Nemeth
          buttons:
            - name: Papers
              url: papers/
            - name: Books
              url: books/
            - name: Software Packages
              url: software/
            - name: Code
              url: code_and_software/
            - name: Research Group
              url: research_group/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            - name: Blog
              url: blogs/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:c.nemeth@lancaster.ac.uk
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=17-Ze24AAAAJ&hl=en
        - name: Orcid
          url: https://orcid.org/0000-0002-9084-3866   
        - name: GitHub
          url: https://github.com/chris-nemeth
        - name: LinkedIn
          url: https://www.linkedin.com/in/christopher-nemeth-815963233

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Chris Nemeth"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
